# Generated by Django 4.1.7 on 2023-03-01 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='modelo')),
                ('capacidad', models.CharField(max_length=100, verbose_name='capacidad')),
                ('no_aplica', models.CharField(max_length=100, verbose_name='no aplica')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema_operativo', models.CharField(choices=[('0', 'Windows'), ('1', 'Linux'), ('2', 'Mac')], max_length=1, verbose_name='Sistema operativo')),
                ('version_sistema_op', models.CharField(choices=[('0', 'Windows 7'), ('1', 'windows 8.1'), ('2', 'windows 10'), ('3', 'windows 11'), ('4', 'debian'), ('5', 'ubuntu'), ('6', 'mint'), ('7', 'fedora'), ('8', 'manjaro'), ('9', 'catalina'), ('10', 'sierra'), ('11', 'monterrey'), ('12', 'bigsufr')], max_length=2, verbose_name='Versión sistema operativo')),
                ('ofimatica', models.CharField(choices=[('0', 'Microsoft office'), ('1', 'Libre office'), ('2', 'Open office'), ('3', 'No instalado')], max_length=1, verbose_name='Ofimatica')),
                ('version_ofimatica', models.CharField(choices=[('0', '2007'), ('1', '2010'), ('2', '2013'), ('3', '2016'), ('4', '2019'), ('5', '365'), ('6', '7.3.5'), ('7', '7.3.4'), ('8', '7.3.3'), ('9', '7.3.2'), ('10', '7.3.1'), ('11', '4.1.3'), ('12', '4.1.2'), ('13', '4.1.1'), ('14', '4.1.0'), ('15', '4.0.0'), ('16', 'No instalado')], max_length=3, verbose_name='Versión ofimatica')),
                ('antivirus', models.CharField(choices=[('0', 'endpoint'), ('1', 'avast'), ('2', 'avg'), ('3', 'kaspersky'), ('4', 'malwarebytes'), ('5', 'bullguard'), ('6', 'No instalado')], default='6', max_length=2, verbose_name='Antivirus')),
                ('navegador', models.CharField(choices=[('0', 'microsoft edge'), ('1', 'mozilla firefox'), ('2', 'google chrome'), ('3', 'opera'), ('4', 'safari'), ('5', 'No instalado')], default='5', max_length=1, verbose_name='Navegador web')),
                ('navegador2', models.CharField(choices=[('0', 'microsoft edge'), ('1', 'mozilla firefox'), ('2', 'google chrome'), ('3', 'opera'), ('4', 'safari'), ('5', 'No instalado')], default='5', max_length=1, verbose_name='Navegador web2')),
                ('herramienta_cloud', models.CharField(choices=[('0', 'google drive'), ('1', 'one drive'), ('2', 'dropbox'), ('3', 'amazon cloud'), ('4', 'No instalado')], max_length=1, verbose_name='Herramienta Cloud')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Hardware'), ('2', 'Software')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=60, verbose_name='marca')),
                ('serie', models.CharField(max_length=90, unique=True, verbose_name='Nro de serie')),
                ('tipo_activo', models.CharField(choices=[('0', 'Computador'), ('1', 'Impresora')], max_length=1, verbose_name='Tipo de activo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('tipo_activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.tipoactivo')),
            ],
        ),
    ]
